{% set version = "0.7.2" %}
{% set sha256 = "c4c5a0ec5f8164774f7d83347c321dd9b37f3b3ed40d30e08b6ffed62bffd8ee" %}

package:
  name: crabz
  version: {{ version }}

source:
  url: https://github.com/sstadick/crabz/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - pkg-config
    - make
    - cmake
    - cargo-bundle-licenses

test:
  commands:
    - crabz --help

about:
  home: https://github.com/sstadick/crabz
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Fast cross platform multi-threaded compression and decompression.

extra:
  recipe-maintainers:
    - sstadick
