{% set version = "0.10.1" %}

package:
  name: crabz
  version: {{ version }}

source:
  url: https://github.com/sstadick/crabz/archive/v{{ version }}.tar.gz
  sha256: fb7833a83db958c8abc3b688a8905385cd19e721133ed0aa1d1dd290ef65d8f0

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - pkg-config
    - make
    - cmake
    - cargo-bundle-licenses

test:
  commands:
    - crabz --help

about:
  home: https://github.com/sstadick/crabz
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Fast cross platform multi-threaded compression and decompression.

extra:
  recipe-maintainers:
    - sstadick
