{% set version = "0.10.0" %}

package:
  name: crabz
  version: {{ version }}

source:
  url: https://github.com/sstadick/crabz/archive/v{{ version }}.tar.gz
  sha256: 2bbd8eb669a6570b104a0eb412d2492d5a9296524964cd676440069d27f52e6c

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - pkg-config
    - make
    - cmake
    - cargo-bundle-licenses

test:
  commands:
    - crabz --help

about:
  home: https://github.com/sstadick/crabz
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Fast cross platform multi-threaded compression and decompression.

extra:
  recipe-maintainers:
    - sstadick
