{% set version = "0.9.0" %}
{% set sha256 = "8b5df26a8ff0b1252d5a31c7135b39aa328e9a256c8869c2e9f346d561e522e7" %}

package:
  name: crabz
  version: {{ version }}

source:
  url: https://github.com/sstadick/crabz/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - pkg-config
    - make
    - cmake
    - cargo-bundle-licenses

test:
  commands:
    - crabz --help

about:
  home: https://github.com/sstadick/crabz
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Fast cross platform multi-threaded compression and decompression.

extra:
  recipe-maintainers:
    - sstadick
